### ISSUE TITLE
2.4Ghz question

### ISSUE THREAD

**Issue by thomasvnl** [d-wsky/RFM73-Lib#1]
Hi,

Why is there a bluetooth nRF58232 chip and antenna inside Tado products when it is supposed to only use 868MHz 6LoWPAN communication?

**Comment by d-wsky** [comment]
Hi Thomas,

thank you for reaching out! Unfortunately, I'm not in a position to publicly disclose any technical details about tado° products. You can rich out [customer support](https://support.tado.com/en/), or any of tado° company profiles at social networks ([Linkedin](https://de.linkedin.com/company/tadogmbh), [Facebook](https://www.facebook.com/tado/) and such) so that the right people could help you with your request.

Anyway, this repo is from 2013 which is a) relates to project I did years before I joined tado°; b) might be even before tado° got their first RF-enabled device 🙂 

If you don't mind, I'll close this issue as not relevant.

--
Best,
Denis.
